/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package anagramkt



import org.junit.Test
import org.junit.Assert


class AppTest {
    @Test fun appHasAGreeting() {
        Assert.assertTrue(true);
    }

    @Test fun appAnother() {
        Assert.assertTrue(true);
    }
}
